spring.application.name=LegalJudgement
spring.datasource.url=jdbc:postgresql://localhost:5432/LawDB
spring.datasource.username=postgres
spring.datasource.password=Success1$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect